name: Hello World Workflow

on:
  push:
    branches:
      - feature-aleksandar  # Adjust this to match your branch name if needed

jobs:
  hello-world:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Print Hello World
        run: echo "Hello, World!"